PROFILS: dict[str, dict] = {
    "sain": {
        "anciennete_mois": 36,
        "sieges_souscrits": 50,
        "utilisateurs_actifs": 45,
        "taux_adoption_pct": 78.0,
        "connexions_30j": 120,
        "heures_usage_30j": 200.0,
        "fonctionnalites_total": 20,
        "fonctionnalites_utilisees": 18,
        "nb_integrations": 5,
        "derniere_connexion_jours": 2,
        "tickets_support_90j": 1,
        "delai_reponse_support_h": 4.0,
        "csat": 8.5,
        "retards_paiement_12m": 0,
        "revenu_mensuel_recurrent_eur": 5000.0,
        "secteur": "Technologie",
        "pays": "France",
        "taille_entreprise": "PME",
        "plan": "Business",
    },
    "surveillance": {
        "anciennete_mois": 14,
        "sieges_souscrits": 20,
        "utilisateurs_actifs": 10,
        "taux_adoption_pct": 35.0,
        "connexions_30j": 15,
        "heures_usage_30j": None,
        "fonctionnalites_total": 16,
        "fonctionnalites_utilisees": 6,
        "nb_integrations": 1,
        "derniere_connexion_jours": 25,
        "tickets_support_90j": 4,
        "delai_reponse_support_h": None,
        "csat": 6.5,
        "retards_paiement_12m": 1,
        "revenu_mensuel_recurrent_eur": 2500.0,
        "secteur": "Finance",
        "pays": "Belgique",
        "taille_entreprise": "TPE",
        "plan": "Pro",
    },
    # Source : dict _COMPTE_RISQUE de notebooks/sections/10_mise_en_exploitation.py
    "alerte": {
        "anciennete_mois": 18,
        "sieges_souscrits": 25,
        "utilisateurs_actifs": 12,
        "taux_adoption_pct": 22.0,
        "connexions_30j": 8,
        "heures_usage_30j": 15.0,
        "fonctionnalites_total": 30,
        "fonctionnalites_utilisees": 6,
        "nb_integrations": 0,
        "derniere_connexion_jours": 42,
        "tickets_support_90j": 9,
        "delai_reponse_support_h": 48.0,
        "csat": 4.5,
        "retards_paiement_12m": 3,
        "revenu_mensuel_recurrent_eur": 3200.0,
        "secteur": "Finance",
        "pays": "France",
        "taille_entreprise": "PME",
        "plan": "Business",
    },
}

LABELS: dict[str, str] = {
    "sain": "✅ Compte sain",
    "surveillance": "⚠️ À surveiller",
    "alerte": "🚨 Compte en alerte",
}
